/* eslint-disable react/no-unescaped-entities */
/* eslint-disable react/jsx-no-target-blank */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import Navbar from "../components/Navbar";
import SectionHero from "../components/SectionHero";
import SectionProducts from "../components/SectionProducts";
import SectionArticle from "../components/SectionArticle";
import SectionTeam from "../components/SectionTeam";
import SectionContact from "../components/SectionContact";
import Footer from "../components/Footer";
import BackToTop from "../components/BackToTop";

export default function Home() {
  return (
    <div>
      <Head>
        <title>
          SKlabs | Powerful integrations for your productivity with LiveChat and
          Intercom
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        id="wow-init"
        strategy="afterInteractive"
        src="/assets/js/wow.min.js"
        onLoad={() => {
          new WOW().init();
        }}
      />

      <Script
        id="main-init"
        strategy="afterInteractive"
        src="/assets/js/main.js"
      />

      <div>
        <Navbar />
        <SectionHero />
        <SectionProducts />

        <SectionArticle
          id="notifications"
          title="Sending Notifications"
          header="We specialize with sending notifications to various channels and manage them all from one place"
          body="Try our Ping integration that allow you to send notifications about chat events to popular channels like: Slack, Microsoft Teams, Discord, SMS and email."
          imageUrl="assets/images/articles/notifications.png"
          link="https://www.livechat.com/marketplace/apps/ping"
        />

        <SectionTeam />
        <SectionContact />

        <Footer />
        <BackToTop />
      </div>
    </div>
  );
}
