/* eslint-disable react/no-unescaped-entities */
/* eslint-disable react/jsx-no-target-blank */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import Navbar from "../components/Navbar";
import SectionHero from "../components/SectionHero";
import SectionProducts from "../components/SectionProducts";
import SectionArticle from "../components/SectionArticle";
import SectionTeam from "../components/SectionTeam";
import SectionContact from "../components/SectionContact";
import Footer from "../components/Footer";
import BackToTop from "../components/BackToTop";

export default function Home() {
  return (
    <div>
      <Head>
        <title>
          SKlabs | Powerful integrations for your productivity with LiveChat and
          Intercom
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        id="wow-init"
        strategy="afterInteractive"
        src="/assets/js/wow.min.js"
        onLoad={() => {
          new WOW().init();
        }}
      />

      <Script
        id="main-init"
        strategy="afterInteractive"
        src="/assets/js/main.js"
      />

      <div>
        <Navbar />
        <SectionHero />
        <SectionProducts />
        <SectionArticle
          id="success"
          title="Success Story"
          header="How SKlabs reached $1k MRR and where they get app ideas"
          body="SKlabs is the author of seven apps, which are available on the LiveChat Marketplace. Last year, they reached the milestone of $1,000 Monthly Recurring Revenue (MRR) and are close to repeating it this year too."
          imageUrl="assets/images/articles/success-story.png"
          link="https://developers.livechat.com/updates/livechat-developer-case-study-sklabs"
        />

        <SectionTeam />
        <SectionContact />

        <Footer />
        <BackToTop />
      </div>
    </div>
  );
}
