/* eslint-disable react/no-unescaped-entities */
/* eslint-disable react/jsx-no-target-blank */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import Navbar from "../components/Navbar";
import SectionHeader from "../components/SectionHeader";
import SectionProducts from "../components/SectionProducts";
import SectionArticle from "../components/SectionArticle";
import SectionTeam from "../components/SectionTeam";
import SectionContact from "../components/SectionContact";
import Footer from "../components/Footer";
import BackToTop from "../components/BackToTop";

export default function Home() {
  return (
    <div>
      <Head>
        <title>
          SKlabs | Powerful integrations for your productivity with LiveChat and
          Intercom
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Script
        src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_ANALYTICS_ID}`}
        strategy="afterInteractive"
      />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){window.dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', '${process.env.NEXT_PUBLIC_ANALYTICS_ID}');
        `}
      </Script>

      <Script
        id="wow-init"
        strategy="afterInteractive"
        src="/assets/js/wow.min.js"
        onLoad={() => {
          new WOW().init();
        }}
      />

      <Script
        id="main-init"
        strategy="afterInteractive"
        src="/assets/js/main.js"
      />

      <div>
        <Navbar />
        <SectionHeader
          header="Powerful integrations for your productivity"
          subheader={
            <>
              We specialize in building powerful integrations for a number of
              platforms, such as{" "}
              <a
                href="https://www.livechat.com/marketplace/"
                target="_blank"
                rel="noreferrer"
                className="text-white hover:opacity-70"
              >
                LiveChat
              </a>{" "}
              and{" "}
              <a
                href="https://www.intercom.com/app-store"
                target="_blank"
                rel="noreferrer"
                className="text-white hover:opacity-70"
              >
                Intercom
              </a>
              .
            </>
          }
          imageUrl="assets/images/hero/hero-image.png"
        />
        <SectionProducts />

        <SectionArticle
          id="notifications"
          title="Sending Notifications"
          header="We specialize with sending notifications to various channels and manage them all from one place"
          body="Try our Ping integration that allow you to send notifications about chat events to popular channels like: Slack, Microsoft Teams, Discord, SMS and email."
          imageUrl="assets/images/articles/notifications.png"
          link="https://www.livechat.com/marketplace/apps/ping"
        />

        <SectionTeam />

        <Footer />
        <BackToTop />
      </div>
    </div>
  );
}
