import Head from "next/head";
import Script from "next/script";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import BackToTop from "../components/BackToTop";
import SectionBanner from "../components/SectionBanner";
import SectionPage from "../components/SectionPage";

export default function Privacy() {
  return (
    <div>
      <Head>
        <title>
          SKlabs | Unlock Your Productivity with Powerful Integrations
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        id="wow-init"
        strategy="afterInteractive"
        src="/assets/js/wow.min.js"
        onLoad={() => {
          new WOW().init();
        }}
      />

      <Script
        id="main-init"
        strategy="afterInteractive"
        src="/assets/js/main.js"
      />

      <div>
        <Navbar isLandingPage />
        <SectionBanner title="Privacy policy" />
        <SectionPage></SectionPage>

        <Footer />
        <BackToTop />
      </div>
    </div>
  );
}
